import { test, expect } from '@playwright/test';

test('welcome, adult onboarding, interpretation and persistent first matches', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: /Find your people/i })).toBeVisible();
  await page.getByRole('button', { name: /Continue with Demo/i }).click();
  await page.getByRole('checkbox', { name: /18 or older/i }).check();
  await page.getByLabel('What should we call you?').fill('Prince');
  await page.getByLabel('Pick a username', { exact: true }).fill('@prince.test');
  await page.getByLabel('Your city', { exact: true }).fill('Jaipur');
  await page.getByRole('button', { name: 'Create together', exact: true }).click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  const film = page.getByRole('button', { name: 'Filmmaking', exact: true }).first();
  if (await film.getAttribute('aria-pressed') !== 'true') await film.click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  const story = page.getByRole('button', { name: 'Storytelling', exact: true }).first();
  if (await story.getAttribute('aria-pressed') !== 'true') await story.click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  const editing = page.getByRole('button', { name: 'Video Editing', exact: true }).first();
  if (await editing.getAttribute('aria-pressed') !== 'true') await editing.click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByLabel('Right now, I’d love to…').fill('I want to start a filmmaking YouTube channel and find someone good at video editing in Jaipur. I can offer storytelling.');
  await page.getByRole('button', { name: 'See my interpretation' }).click();
  await expect(page.getByText('Our interpretation · editable')).toBeVisible();
  await expect(page.getByLabel('Your original words')).toHaveValue(/filmmaking YouTube/);
  await page.getByRole('button', { name: 'Find my people' }).click();
  await page.waitForURL(/first-matches/);
  await expect(page.getByText('Aarav', { exact: false }).first()).toBeVisible();
  await page.screenshot({ path: 'test-results/first-matches.png', fullPage: true });
  await page.reload();
  await expect(page.getByText('Aarav', { exact: false }).first()).toBeVisible();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('nexus-mvp-state-v1') || '{}'));
  expect(saved.onboardingComplete).toBe(true);
  expect(saved.users.find((user: { id: string }) => user.id === saved.meId).username).toBe('prince.test');
  expect(await page.evaluate(() => sessionStorage.getItem('nexus-onboarding-draft-v1'))).toBeNull();
  expect(saved.intents.some((item: { originalText: string }) => item.originalText.includes('filmmaking YouTube'))).toBe(true);
  const aarav = page.locator('article').filter({ hasText: 'Aarav Mehta' }).first();
  await aarav.getByRole('button', { name: 'View profile' }).click();
  await expect(page.getByText('WHY YOU TWO SHOULD CONNECT', { exact: true })).toBeVisible();
  await page.goBack();
  await aarav.getByRole('button', { name: 'Connect', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByLabel('Why would you like to connect?').fill('Let’s make a Jaipur short film. I can offer storytelling and would love your editing help.');
  await page.getByRole('button', { name: 'Send connection request' }).click();
  await expect(aarav.getByRole('button', { name: 'Requested' })).toBeDisabled();
  await page.goto('/#inbox/requests');
  await page.getByRole('button', { name: 'Accept as Aarav (demo)' }).click();
  await page.waitForURL(/chat/);
  await expect(page.getByRole('article', { name: 'NEXUS introduction', exact: true })).toHaveCount(1);
  await page.getByRole('button', { name: 'Discuss a project' }).click();
  await expect(page.getByLabel('Message Aarav Mehta')).toHaveValue(/small project/);
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect(page.getByRole('article', { name: 'Your message', exact: true })).toHaveCount(1);
  await expect(page.getByRole('article', { name: "Aarav Mehta's message", exact: true })).toHaveCount(1);
  await expect(page.getByLabel('Read', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('article', { name: 'NEXUS introduction', exact: true })).toHaveCount(1);
  await expect(page.getByRole('article', { name: 'Your message', exact: true })).toHaveCount(1);
  await page.getByRole('button', { name: 'Back to Inbox' }).click();
  await page.getByRole('button', { name: 'Back to Home' }).click();
  await expect(page.getByRole('heading', { name: /Good things start/ })).toBeVisible();
  await page.getByRole('button', { name: 'Discover', exact: true }).click();
  await page.getByLabel('Search discovery').fill('zz-no-matches');
  await expect(page.getByText('No people found', { exact: true })).toBeVisible();
  await page.getByLabel('Search discovery').fill('');
  await page.getByRole('tab', { name: 'INTENTS', exact: true }).click();
  await expect(page.getByText('What people want to do', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'CIRCLES', exact: true }).click();
  await page.getByLabel('Search discovery').fill('Ship Something');
  await page.getByRole('button', { name: 'Explore circle' }).click();
  await expect(page.getByRole('heading', { name: 'Ship Something Small' })).toBeVisible();
  await page.getByRole('button', { name: 'Join circle', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Leave circle' })).toBeVisible();
  for (const name of ['People', 'Projects', 'Events', 'Discuss']) {
    await page.getByRole('tab', { name, exact: true }).click();
    await expect(page.getByRole('tabpanel', { name, exact: true })).toBeVisible();
  }
  await page.getByRole('button', { name: 'Post', exact: true }).click();
  await page.getByRole('button', { name: 'Collaborate', exact: true }).click();
  await page.getByLabel('What do you want to build together?').fill('A tiny film-planning app');
  await page.getByLabel('Describe the project, what you bring, and who you need.').fill('I bring storytelling. Looking for a designer to prototype a simple shot list together.');
  await page.getByLabel('Skills needed (comma separated)').fill('design, React');
  await page.getByLabel('Location', { exact: true }).fill('Jaipur');
  await page.getByLabel('Time commitment / timeline').fill('Two weekends');
  await page.getByRole('button', { name: 'Publish post' }).click();
  await expect(page.getByRole('heading', { name: 'A little spark, shared.' })).toBeVisible();
  await page.getByRole('button', { name: 'Go to circle' }).click();
  await expect(page.getByRole('heading', { name: 'A tiny film-planning app' })).toBeVisible();
  const post = page.locator('article').filter({ hasText: 'A tiny film-planning app' });
  await post.getByRole('button', { name: /^Useful/ }).click();
  await expect(post.getByRole('button', { name: /^Useful/ })).toHaveAttribute('data-selected', 'true');
  await page.reload();
  await expect(page.getByRole('heading', { name: 'A tiny film-planning app' })).toBeVisible();
  expect(errors).toEqual([]);
});
