import { useState } from 'react';
import { Flag, Handshake, MessageSquare, Send, Lightbulb } from 'lucide-react';
import type { Post, Reaction } from '../domain/types';
import { useActions, useBlockedIds, useCircles, useMe, useUser } from '../repo/store';
import { navigate } from '../routerStore';
import { Avatar } from './Avatar';
import { ReportDialog } from './ReportDialog';
const reactions: [Reaction, string][] = [['useful', 'Useful'], ['interesting', 'Interesting'], ['lets-do-it', "Let’s do it"], ['support', 'Support']];
export function PostCard({ post }: { post: Post }) {
  const actions = useActions(); const user = useUser(post.userId); const me = useMe(); const blocked = useBlockedIds(); const circles = useCircles();
  const [comments, setComments] = useState(false); const [text, setText] = useState(''); const [error, setError] = useState(''); const [report, setReport] = useState(false);
  const circle = circles.find(c => c.id === post.circleId);
  if (!user || user.suspended || blocked.includes(user.id) || (post.circleId && (!circle || (circle.privacy !== 'open' && !circle.memberIds.includes(me.id))))) return null;
  const run = (fn: () => void) => { try { fn(); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save. Please try again.'); } };
  return <article className="card p-5 space-y-3"><header className="flex gap-2 items-center"><button className="flex items-center gap-2 min-h-11 text-left flex-1" onClick={() => navigate('user', user.id)}><Avatar user={user} size={38} /><span><span className="block text-sm font-semibold">{user.name}</span><span className="eyebrow">{post.kind} · {new Date(post.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</span></span></button><button className="btn btn-ghost px-3" disabled={me.suspended} onClick={() => setReport(true)} aria-label="Report post"><Flag size={16} /></button></header><h3 className="text-lg font-bold">{post.title}</h3><p className="text-sm leading-relaxed whitespace-pre-wrap break-words" style={{ color: 'var(--text-2)' }}>{post.body}</p>{post.structured && <p className="text-xs" style={{ color: 'var(--accent-text)' }}>{post.structured.location || 'Remote'} · {post.structured.time || 'Flexible'} · {post.structured.paid ? 'Paid' : 'Unpaid collaboration'}</p>}<div className="flex flex-wrap gap-2">{post.tags.map(t => <span className="eyebrow" key={t}>#{t}</span>)}</div><div className="divider" /><div className="flex flex-wrap gap-1">{reactions.map(([key, label]) => <button key={key} className="chip min-h-11" disabled={me.suspended} data-selected={post.myReaction === key} onClick={() => run(() => { actions.posts.react(post.id, key); })}>{key === 'useful' && <Lightbulb size={14} />}{label} {post.reactions[key] || ''}</button>)}</div><div className="flex justify-between gap-2"><button className="btn btn-ghost px-2 text-sm" onClick={() => setComments(!comments)} aria-expanded={comments}><MessageSquare size={16} />{post.comments.length} comments</button>{user.id !== me.id && <button className="btn btn-ghost px-2 text-sm" disabled={me.suspended || post.iCanHelp || post.helpedBy.includes(me.id)} onClick={() => run(() => { actions.posts.icanHelp(post.id); })}><Handshake size={16} />{post.iCanHelp || post.helpedBy.includes(me.id) ? 'Help offered' : 'I can help'}</button>}</div>{error && <p role="alert" style={{ color: 'var(--danger)' }}>{error}</p>}{comments && <section className="space-y-3">{post.comments.length === 0 && <p className="text-sm" style={{ color: 'var(--text-3)' }}>Start a thoughtful conversation.</p>}{post.comments.filter(c => !blocked.includes(c.userId)).map(c => <Comment key={c.id} comment={c} />)}<form className="flex gap-2" onSubmit={e => { e.preventDefault(); run(() => { actions.posts.comment(post.id, text); setText(''); }); }}><input className="input min-w-0" aria-label="Write a comment" placeholder="Add something useful…" value={text} maxLength={3000} onChange={e => setText(e.target.value)} /><button className="btn btn-primary px-3" aria-label="Send comment" disabled={!text.trim() || me.suspended}><Send size={18} /></button></form></section>}<ReportDialog open={report} onClose={() => setReport(false)} targetKind="post" targetId={post.id} targetLabel="post" /></article>;
}
function Comment({ comment }: { comment: Post['comments'][number] }) { const author = useUser(comment.userId); return <div className="rounded-xl p-3 text-sm" style={{ background: 'var(--surface-2)' }}><strong>{author?.name ?? 'NEXUS member'}</strong><p className="whitespace-pre-wrap break-words">{comment.text}</p></div>; }
export default PostCard;
