import { useState } from 'react';
import { Search, SlidersHorizontal } from 'lucide-react';
import { useBlockedIds, useCircles, useIntents, useMe, useUsers } from '../repo/store';
import { People } from './People';
import { IntentCard } from '../components/IntentCard';
import { CircleCard } from '../components/CircleCard';
import { EmptyState } from '../components/EmptyState';
import { navigate } from '../routerStore';
export function Discover() {
  const [tab, setTab] = useState<'PEOPLE' | 'INTENTS' | 'CIRCLES'>('PEOPLE'); const [query, setQuery] = useState(''); const intents = useIntents(); const circles = useCircles(); const me = useMe(); const users = useUsers(); const blocked = useBlockedIds();
  const shownIntents = intents.filter(i => i.visibility === 'public' && i.status === 'active' && (i.expiresAt === null || i.expiresAt > Date.now()) && !blocked.includes(i.userId) && !users.find(u => u.id === i.userId)?.suspended && `${i.title} ${i.originalText} ${i.interpretation.domain}`.toLowerCase().includes(query.toLowerCase()));
  const shownCircles = circles.filter(c => `${c.name} ${c.purpose} ${c.category}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="p-5 pb-8 space-y-5"><header><p className="eyebrow">Make room for possibility</p><h1 className="text-3xl font-bold tracking-tight mt-2">Discover</h1><p className="text-sm mt-2" style={{ color: 'var(--text-2)' }}>Your next good thing starts with someone.</p></header><div className="relative"><Search size={18} className="absolute left-4 top-4" style={{ color: 'var(--text-3)' }} /><input className="input pl-11" value={query} onChange={e => setQuery(e.target.value)} placeholder="People, skills, ideas, circles…" aria-label="Search discovery" /></div><div className="flex gap-1 rounded-full p-1" role="tablist" aria-label="Discover category" style={{ background: 'var(--surface-2)' }}>{(['PEOPLE', 'INTENTS', 'CIRCLES'] as const).map(t => <button key={t} role="tab" aria-selected={tab === t} className={`btn flex-1 px-2 text-xs ${tab === t ? 'btn-primary' : 'btn-ghost'}`} onClick={() => setTab(t)}>{t}</button>)}</div><div role="tabpanel" aria-label={tab} className="space-y-4">{tab === 'PEOPLE' && <><div className="flex justify-between items-center"><h2 className="eyebrow">People you should know</h2><button className="btn btn-ghost px-2 text-xs" onClick={() => navigate('edit-profile')}><SlidersHorizontal size={15} />Refine profile</button></div><People embedded search={query} /></>}{tab === 'INTENTS' && <><p className="eyebrow">What people want to do</p>{shownIntents.map(i => <IntentCard key={i.id} intent={i} />)}{!shownIntents.length && <EmptyState title="No intents found" description="Try a different search, or put your own idea out there." actionLabel="Share an intent" onAction={() => navigate('create')} />}</>}{tab === 'CIRCLES' && <><p className="eyebrow">Small groups. Shared purpose.</p>{shownCircles.map(c => <CircleCard key={c.id} circle={c} />)}{!shownCircles.length && <EmptyState title="Your circle could be the first" description="Try another search or gather people around a goal." actionLabel={me.suspended ? undefined : 'Create a circle'} onAction={() => navigate('create', 'circle')} />}</>}</div></div>;
}
export default Discover;
