import { useState } from 'react';
import { ArrowLeft, MoreHorizontal, Flag, Ban, MapPin, ShieldCheck, Sparkles, MessageSquare } from 'lucide-react';
import { useActions, useBlockedIds, useCircleProjects, useConnections, useConversations, useIntents, useMe, useRequests, useUser, useNexus } from '../repo/store';
import { interestLabel, skillLabel, AVAILABILITY_LABELS } from '../domain/ontology';
import { matchPerson } from '../services/intelligence';
import { back, navigate, useRoute } from '../routerStore';
import { Avatar } from '../components/Avatar';
import { EmptyState } from '../components/EmptyState';
import { FitBadge } from '../components/FitBadge';
import { Sheet } from '../components/Sheet';
import { Modal } from '../components/Modal';
import { ReportDialog } from '../components/ReportDialog';
import { ProfileStats } from '../components/ProfileStats';
export function UserDetail({ id, userId }: { id?: string; userId?: string } = {}) {
  const { route } = useRoute(); const user = useUser(id ?? userId ?? route.param); const me = useMe(); const intents = useIntents(); const projects = useCircleProjects(); const blocked = useBlockedIds(); const actions = useActions(); const requests = useRequests(); const connections = useConnections(); const conversations = useConversations();
  const signedIn = useNexus(state => state.signedIn);
  const following = useNexus(state => state.follows.some(item => item.fromUserId === state.meId && item.toUserId === user?.id));
  const [notice, setNotice] = useState('');
  const [menu, setMenu] = useState(false); const [report, setReport] = useState(false); const [block, setBlock] = useState(false); const [connect, setConnect] = useState(false); const [why, setWhy] = useState(''); const [error, setError] = useState('');
  if (!user || !me) return <div className="p-5"><EmptyState title="Profile unavailable" description="This person may no longer be on NEXUS." actionLabel="Discover people" onAction={() => navigate('discover')} /></div>
;
  const own = user.id === me.id; const disabled = !!(!signedIn || me.suspended || user.suspended || blocked.includes(user.id)); const match = matchPerson(me, user, intents); const pending = requests.find(r => r.status === 'pending' && ((r.fromUserId === me.id && r.toUserId === user.id) || (r.toUserId === me.id && r.fromUserId === user.id))); const connected = connections.some(c => [c.aUserId, c.bUserId].includes(me.id) && [c.aUserId, c.bUserId].includes(user.id)); const conversation = conversations.find(c => c.memberIds.includes(user.id) && c.memberIds.includes(me.id));
  const run = (fn: () => void) => { try { fn(); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to complete that action.'); } };
  const sections = [['WHO I AM', user.bio], ['CURRENTLY', user.currently]];
  return <div className="p-5 pb-8 space-y-5"><header className="flex justify-between"><button className="btn btn-ghost px-3" onClick={back} aria-label="Go back"><ArrowLeft size={21} /></button><span className="eyebrow self-center">NEXUS Passport</span>{!own ? <button className="btn btn-ghost px-3" onClick={() => setMenu(true)} aria-label="Profile options"><MoreHorizontal size={22} /></button> : <span className="w-11" />}</header><div className="text-center space-y-2"><Avatar user={user} size={96} /><h1 className="text-3xl font-bold tracking-tight">{user.name}</h1><p style={{ color: 'var(--text-2)' }}>{user.headline}</p><p className="text-xs flex items-center justify-center gap-1" style={{ color: 'var(--text-3)' }}>{user.privacy.showCity && user.city && <><MapPin size={12} />{user.city} · </>}{AVAILABILITY_LABELS[user.availability]}</p>{!own && <FitBadge fit={match.fit} />}</div>
<ProfileStats userId={user.id} />
{!own && <button className="btn btn-secondary w-full" disabled={!signedIn || !!me.suspended || (!following && (disabled || !user.privacy.discoverable))} onClick={() => run(() => { if (following) actions.follows.unfollow(user.id); else actions.follows.follow(user.id); })}>{following ? 'Unfollow' : 'Follow'}</button>}
{(user.suspended || blocked.includes(user.id) || me.suspended) && <p className="card p-4 text-sm" role="status">{user.suspended ? 'This account is suspended. Interactions are unavailable.' : blocked.includes(user.id) ? 'You have blocked this person. Manage this in Settings → Blocked people.' : 'Your account is suspended. Interactions are unavailable.'}</p>}<div className="flex flex-wrap justify-center gap-2">{user.trustBadges.map(b => <span className="chip" key={b} style={{ cursor: 'default' }}><ShieldCheck size={14} style={{ color: 'var(--good)' }} />{b.replace(/-/g, ' ')} verified</span>)}</div>
<div className="nexus-line" />{sections.map(([title, body]) => <section key={title}><h2 className="eyebrow mb-2">{title}</h2><p className="text-sm leading-relaxed" style={{ color: 'var(--text-2)' }}>{body || 'Still taking shape.'}</p></section>)}{[['INTERESTS', user.interests.map(interestLabel)], ['CAN HELP WITH', user.skills.map(skillLabel)], ['LOOKING FOR', user.needs.map(skillLabel)]].map(([title, items]) => <section key={String(title)}><h2 className="eyebrow mb-3">{title}</h2><div className="flex flex-wrap gap-2">{(items as string[]).length ? (items as string[]).map(item => <span className="chip" style={{ cursor: 'default' }} key={item}>{item}</span>) : <p className="text-sm" style={{ color: 'var(--text-3)' }}>Not added yet.</p>}</div>
</section>)}<section className="space-y-3"><h2 className="eyebrow">Projects</h2>{projects.filter(p => p.ownerUserId === user.id).map(p => <button key={p.id} className="card p-4 w-full text-left min-h-11" onClick={() => navigate('circle', p.circleId)}><span className="font-semibold text-sm">{p.title}</span><span className="eyebrow block mt-1">{p.status === 'done' ? 'Completed' : 'In progress'} · View circle →</span></button>)}{!projects.some(p => p.ownerUserId === user.id) && <p className="text-sm" style={{ color: 'var(--text-3)' }}>New projects have room to begin.</p>}</section><section className="card p-4"><h2 className="eyebrow mb-4">Reputation · built by contributing</h2><div className="grid grid-cols-3 gap-2 text-center">{[[user.reputation.peopleHelped, 'People helped'], [user.reputation.projectsCompleted, 'Projects done'], [user.reputation.collaborations, 'Collaborations']].map(([n, label]) => <div key={label}><strong className="text-xl block">{n}</strong><span className="text-xs" style={{ color: 'var(--text-3)' }}>{label}</span></div>
)}</div>
</section>{!own && <section className="card p-5 space-y-3" style={{ background: 'var(--accent-soft)' }}><h2 className="eyebrow" style={{ color: 'var(--accent-text)' }}>WHY YOU TWO SHOULD CONNECT</h2>{match.reasons.length ? match.reasons.map((r, i) => <p className="flex gap-2 text-sm" key={i}><Sparkles size={15} className="shrink-0 mt-1" />{r.text}</p>) : <p className="text-sm">There is more to discover through a thoughtful introduction.</p>}</section>}{error && <p role="alert" style={{ color: 'var(--danger)' }}>{error}</p>}{own ? <button className="btn btn-primary w-full" onClick={() => navigate('edit-profile')}>Edit your passport</button> : connected && conversation ? <button className="btn btn-primary w-full" disabled={disabled} onClick={() => navigate('chat', conversation.id)}><MessageSquare size={18} />Open conversation</button> : <button className="btn btn-primary w-full" disabled={disabled || !!pending || connected} onClick={() => { setWhy(match.reasons.slice(0, 2).map(r => r.text).join(' ') || `I'd like to connect around ${user.currently || user.headline}.`); setConnect(true); }}>{pending ? pending.fromUserId === me.id ? 'Connection requested' : 'Incoming connection request' : connected ? 'Connected' : `Connect with ${user.name.split(' ')[0]}`}</button>}{!own && !connected && pending?.fromUserId === me.id && <button className="btn btn-secondary w-full" disabled={!signedIn || !!me.suspended} onClick={() => run(() => { actions.connections.cancel(pending.id); setNotice('Connection request cancelled.'); })}>Cancel request</button>}{!own && !connected && pending?.toUserId === me.id && <button className="btn btn-secondary w-full" onClick={() => navigate('inbox', 'requests')}>Review request in Inbox</button>}{notice && <p role="status" className="text-sm text-[var(--text-2)]">{notice}</p>}<Sheet open={connect} onClose={() => setConnect(false)} title="Start with a reason"><form className="space-y-4" onSubmit={e => { e.preventDefault(); run(() => { actions.connections.request(user.id, why); setConnect(false); }); }}><label className="block text-sm">Why do you want to connect?<textarea className="input mt-2" rows={5} required maxLength={1000} value={why} onChange={e => setWhy(e.target.value)} /></label>{error && <p role="alert">{error}</p>}<button className="btn btn-primary w-full" disabled={disabled || !why.trim()}>Send connection request</button></form></Sheet><Sheet open={menu} onClose={() => setMenu(false)} title="Profile options"><div className="space-y-2"><button className="btn btn-ghost w-full justify-start" disabled={me.suspended || user.suspended} onClick={() => { setMenu(false); setReport(true); }}><Flag size={18} />Report {user.name.split(' ')[0]}</button><button className="btn btn-danger w-full justify-start" disabled={disabled} onClick={() => { setMenu(false); setBlock(true); }}><Ban size={18} />Block {user.name.split(' ')[0]}</button></div>
</Sheet><Modal open={block} onClose={() => setBlock(false)} title={`Block ${user.name.split(' ')[0]}?`}><p className="text-sm mb-4">They will be removed from your suggestions and you will no longer exchange messages. You can unblock them in settings.</p><div className="flex gap-2"><button type="button" className="btn btn-secondary flex-1" onClick={() => setBlock(false)}>Cancel</button><button type="button" className="btn btn-danger flex-1" disabled={disabled} onClick={() => run(() => { actions.blocks.add(user.id); setBlock(false); })}>Block person</button></div>
{error && <p role="alert">{error}</p>}</Modal><ReportDialog open={report} onClose={() => setReport(false)} targetKind="user" targetId={user.id} targetLabel={user.name} /></div>
;
}
export default UserDetail;
